[theme]
primaryColor = "#419b90ff" #elementos interativos
backgroundColor = "#000000" #cor de fundo
secondaryBackgroundColor = "#004d44" #sidebar
textColor = "#ffffffff" #cor do texto
font = "san serif" 

